"""FHIR R4-compatible patient definitions for the 8 synthetic ED patients."""
from datetime import datetime, timedelta
from models.schemas import Patient, Medication, CodeStatus, Sex


def _ts(minutes_ago: int) -> str:
    dt = datetime.utcnow() - timedelta(minutes=minutes_ago)
    return dt.isoformat() + "Z"


SYNTHETIC_PATIENTS: list[Patient] = [
    Patient(
        id="p001",
        mrn="MRN-00847",
        name="James Wilson",
        age=67,
        sex=Sex.M,
        dob="1957-03-14",
        chief_complaint="Chest pain",
        arrival_time=_ts(95),
        bed="ED-Bay-4",
        attending="Dr. Sarah Chen",
        code_status=CodeStatus.FULL,
        allergies=["Penicillin", "Sulfa"],
        current_medications=[
            Medication(name="Metoprolol", dose="50mg", route="PO", frequency="BID", started=_ts(120)),
            Medication(name="Lisinopril", dose="10mg", route="PO", frequency="QD", started=_ts(120)),
            Medication(name="Aspirin", dose="81mg", route="PO", frequency="QD", started=_ts(120)),
        ],
        active_conditions=["Hypertension", "Type 2 Diabetes Mellitus", "Coronary Artery Disease"],
        acuity=2,
    ),
    Patient(
        id="p002",
        mrn="MRN-01234",
        name="Maria Santos",
        age=34,
        sex=Sex.F,
        dob="1990-07-22",
        chief_complaint="Shortness of breath",
        arrival_time=_ts(42),
        bed="ED-Bay-7",
        attending="Dr. Michael Torres",
        code_status=CodeStatus.FULL,
        allergies=["NSAIDs"],
        current_medications=[
            Medication(name="Albuterol", dose="2.5mg", route="Nebulized", frequency="PRN", started=_ts(50)),
            Medication(name="Prenatal vitamins", dose="1 tab", route="PO", frequency="QD", started=_ts(200)),
        ],
        active_conditions=["Asthma", "Pregnancy (28 weeks)"],
        acuity=2,
    ),
    Patient(
        id="p003",
        mrn="MRN-02951",
        name="Robert Chen",
        age=78,
        sex=Sex.M,
        dob="1946-11-08",
        chief_complaint="Altered mental status",
        arrival_time=_ts(120),
        bed="ED-Bay-1",
        attending="Dr. Sarah Chen",
        code_status=CodeStatus.DNR,
        allergies=["Codeine"],
        current_medications=[
            Medication(name="Warfarin", dose="5mg", route="PO", frequency="QD", started=_ts(300)),
            Medication(name="Amlodipine", dose="10mg", route="PO", frequency="QD", started=_ts(300)),
            Medication(name="Donepezil", dose="10mg", route="PO", frequency="QHS", started=_ts(300)),
        ],
        active_conditions=["Dementia", "Hypertension", "Atrial Fibrillation"],
        acuity=1,
    ),
    Patient(
        id="p004",
        mrn="MRN-03388",
        name="Sarah Johnson",
        age=45,
        sex=Sex.F,
        dob="1979-05-30",
        chief_complaint="Abdominal pain",
        arrival_time=_ts(65),
        bed="ED-Bay-9",
        attending="Dr. James Park",
        code_status=CodeStatus.FULL,
        allergies=[],
        current_medications=[
            Medication(name="Ibuprofen", dose="400mg", route="PO", frequency="PRN", started=_ts(70)),
        ],
        active_conditions=[],
        acuity=3,
    ),
    Patient(
        id="p005",
        mrn="MRN-04672",
        name="Michael Brown",
        age=52,
        sex=Sex.M,
        dob="1972-09-16",
        chief_complaint="Syncope",
        arrival_time=_ts(55),
        bed="ED-Bay-3",
        attending="Dr. Michael Torres",
        code_status=CodeStatus.FULL,
        allergies=["Aspirin"],
        current_medications=[
            Medication(name="Digoxin", dose="0.125mg", route="PO", frequency="QD", started=_ts(150)),
            Medication(name="Tiotropium", dose="18mcg", route="Inhaled", frequency="QD", started=_ts(150)),
        ],
        active_conditions=["Heart block (complete)", "COPD"],
        acuity=2,
    ),
    Patient(
        id="p006",
        mrn="MRN-05119",
        name="Emily Davis",
        age=28,
        sex=Sex.F,
        dob="1996-02-11",
        chief_complaint="Seizure",
        arrival_time=_ts(30),
        bed="ED-Bay-2",
        attending="Dr. Sarah Chen",
        code_status=CodeStatus.FULL,
        allergies=["Phenytoin"],
        current_medications=[
            Medication(name="Levetiracetam", dose="500mg", route="PO", frequency="BID", started=_ts(100)),
        ],
        active_conditions=["Epilepsy"],
        acuity=1,
    ),
    Patient(
        id="p007",
        mrn="MRN-06843",
        name="Thomas Lee",
        age=61,
        sex=Sex.M,
        dob="1963-12-03",
        chief_complaint="Back pain",
        arrival_time=_ts(150),
        bed="ED-Bay-11",
        attending="Dr. James Park",
        code_status=CodeStatus.FULL,
        allergies=["Contrast dye"],
        current_medications=[
            Medication(name="Amlodipine", dose="5mg", route="PO", frequency="QD", started=_ts(200)),
            Medication(name="Furosemide", dose="40mg", route="PO", frequency="QD", started=_ts(200)),
        ],
        active_conditions=["CKD Stage 3", "Hypertension"],
        acuity=4,
    ),
    Patient(
        id="p008",
        mrn="MRN-07562",
        name="Nancy White",
        age=83,
        sex=Sex.F,
        dob="1941-08-25",
        chief_complaint="Fall",
        arrival_time=_ts(80),
        bed="ED-Bay-6",
        attending="Dr. Michael Torres",
        code_status=CodeStatus.DNI,
        allergies=["Morphine", "Latex"],
        current_medications=[
            Medication(name="Warfarin", dose="3mg", route="PO", frequency="QD", started=_ts(400)),
            Medication(name="Furosemide", dose="80mg", route="PO", frequency="QD", started=_ts(400)),
            Medication(name="Digoxin", dose="0.125mg", route="PO", frequency="QD", started=_ts(400)),
            Medication(name="Carvedilol", dose="12.5mg", route="PO", frequency="BID", started=_ts(400)),
        ],
        active_conditions=["Osteoporosis", "Atrial Fibrillation", "Congestive Heart Failure"],
        acuity=2,
    ),
]

PATIENTS_BY_ID: dict[str, Patient] = {p.id: p for p in SYNTHETIC_PATIENTS}
